version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:5000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/supportchat
      - JWT_SECRET=your_jwt_secret
      - OPENROUTER_API_KEY=your_openrouter_api_key
      - NODE_ENV=development

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: